name: "Google Cloud Storage Bucket Sync (GCP,GCS)"
description: "Sync a Github repository with a Google Cloud Storage (GCS) bucket"
author: "Nick Forbes-Smith"

inputs:
  secrets:
    description: Google credentials
    required: true
  bucket:
    description: Bucket name
    required: true
  cachecontrol:
    description: Cache control (in seconds)
    required: false
    default: "300"
  compress:
    description: Compress files
    required: false
    default: "true"
  exclude:
    description: Regex for excluding files/dirs
    required: false
    default: ".git$"

runs:
  using: docker
  image: Dockerfile
branding:
  icon: arrow-up
  color: gray-dark
